_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 15
                - 16
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 256
dataset:
    value: EuroSAT
epochs:
    value: 60
feature_dim:
    value: 512
learning_rate:
    value: 0.000375
model:
    value: SimCLR
pretrained:
    value: false
proj_dim:
    value: 64
seed:
    value: 42
temperature:
    value: 0.2
